# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoAgentDialog
                                 A QGIS plugin
 Plugin for geospatial workflow
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tek Kshetri
        email                : iamtekson@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "geo_agent_dialog_base.ui")
)


class GeoAgentDialog(QtWidgets.QDockWidget, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeoAgentDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Set default values for UI controls
        self._set_defaults()

    def _set_defaults(self):
        """Set default values for dialog controls."""
        try:
            # Set temperature to 0.8
            if hasattr(self, "temperature"):
                self.temperature.setValue(0.8)
        except Exception:
            pass

        try:
            # Set max tokens to 5000
            if hasattr(self, "max_tokens"):
                self.max_tokens.setValue(5000)
        except Exception:
            pass

        try:
            # Set Ollama model name to llama3.2:3b
            if hasattr(self, "ollama_model_name"):
                self.ollama_model_name.setText("llama3.2:3b")
        except Exception:
            pass

        try:
            # Set Ollama base URL
            if hasattr(self, "ollama_base_url"):
                self.ollama_base_url.setText("http://localhost:11434")
        except Exception:
            pass
