# -*- coding: utf-8 -*-
"""
Export a processing-mode run as a QGIS Processing model (.model3).

Every successful geoprocessing step becomes a child algorithm, wired the way
it actually ran:

- a parameter that consumed an earlier step's output -> that child's output
- a project layer or file the user supplied -> a model input (defaulting to
  that layer), so the model can be re-run on other data
- anything else -> a static value
- results no later step consumed -> model outputs

The model can then be opened in QGIS's own Model Designer or saved to file.
"""
import os
import re
from typing import Any, Dict, List, Optional, Tuple

from qgis.PyQt.QtCore import QPointF
from qgis.core import (
    QgsApplication,
    QgsProcessingModelAlgorithm,
    QgsProcessingModelChildAlgorithm,
    QgsProcessingModelChildParameterSource,
    QgsProcessingModelOutput,
    QgsProcessingModelParameter,
    QgsProject,
)

from ..tools.geoprocessing import LAYER_PARAM_TYPES
from ..logger.processing_logger import get_processing_logger

_logger = get_processing_logger()

MODEL_GROUP = "GeoAgent"

# Designer layout: inputs in a top row, steps below by dependency depth
_X0, _X_STEP = 160.0, 300.0
_INPUT_Y, _CHILD_Y0, _Y_STEP = 60.0, 200.0, 140.0


def collect_steps(task_results: Optional[Dict[Any, Dict[str, Any]]]) -> List[Dict[str, Any]]:
    """Successful geoprocessing steps of a run, in task order."""

    def order(item: Tuple[Any, Dict[str, Any]]) -> int:
        try:
            return int(item[0])
        except (TypeError, ValueError):
            return 0

    steps = []
    for task_id, result in sorted((task_results or {}).items(), key=order):
        step = (result or {}).get("step")
        if result.get("success") and step and step.get("algorithm"):
            steps.append({"task_id": task_id, "operation": result.get("operation", ""), **step})
    return steps


def _model_name(request: str) -> str:
    text = re.sub(r'[\\/:*?"<>|\s]+', " ", request or "").strip()
    if len(text) > 60:
        text = text[:60].rsplit(" ", 1)[0]
    return f"GeoAgent - {text}" if text else "GeoAgent model"


def suggested_file_name(model: QgsProcessingModelAlgorithm) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", model.name()).strip("_").lower()
    return f"{slug or 'geoagent_model'}.model3"


def _slug(text: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", text or "").strip("_").lower()
    return slug or "input"


class _ModelBuilder:
    """Builds one QgsProcessingModelAlgorithm from recorded steps."""

    def __init__(self, request: str):
        self.project = QgsProject.instance()
        self.registry = QgsApplication.processingRegistry()
        self.model = QgsProcessingModelAlgorithm(_model_name(request), MODEL_GROUP)
        if request:
            self.model.setHelpContent(
                {"ALG_DESC": f"Generated by GeoAgent from the request: {request}"}
            )
        self.producers: Dict[str, Tuple[str, str]] = {}  # layer id -> (child id, output)
        self.consumed: set = set()  # layer ids used by a later step
        self.inputs: Dict[str, str] = {}  # layer id / path -> model parameter name
        self.depth: Dict[str, int] = {}  # child id -> depth

    # ── layer references ────────────────────────────────────────────────────
    def _layer(self, ref: Any):
        if not isinstance(ref, str) or not ref:
            return None
        layer = self.project.mapLayer(ref)
        if layer is None:
            by_name = self.project.mapLayersByName(ref)
            layer = by_name[0] if len(by_name) == 1 else None
        return layer

    def _produced(self, ref: Any) -> Optional[Tuple[str, str]]:
        layer = self._layer(ref)
        key = layer.id() if layer is not None else ref
        if isinstance(key, str) and key in self.producers:
            self.consumed.add(key)
            return self.producers[key]
        return None

    def _input_label(self, ref: Any) -> Tuple[str, Any]:
        """(label, default value) for a model input fed by a project layer/path."""
        layer = self._layer(ref)
        if layer is not None:
            return layer.name(), layer.name()
        if isinstance(ref, str) and os.path.exists(ref.split("|")[0]):
            return os.path.splitext(os.path.basename(ref.split("|")[0]))[0], ref
        return str(ref), ref

    def _add_input(self, key: str, definition, label: str, default: Any) -> str:
        if key in self.inputs:
            return self.inputs[key]
        taken = set(self.model.parameterComponents().keys())
        name, i = _slug(label), 2
        while name in taken:
            name, i = f"{_slug(label)}_{i}", i + 1
        param = definition.clone()
        param.setName(name)
        param.setDescription(label)
        param.setDefaultValue(default)
        component = QgsProcessingModelParameter(name)
        component.setPosition(QPointF(_X0 + _X_STEP * len(self.inputs), _INPUT_Y))
        self.model.addModelParameter(param, component)
        self.inputs[key] = name
        return name

    def _layer_sources(self, definition, value: Any) -> Tuple[list, int]:
        """Sources for a layer parameter, and the depth they imply."""
        Src = QgsProcessingModelChildParameterSource
        refs = value if isinstance(value, list) else [value]
        produced = [self._produced(r) for r in refs]
        depth = max(
            (self.depth[p[0]] + 1 for p in produced if p is not None), default=0
        )

        if not any(produced):
            # All user data: one model input (a list input for multi-layer)
            labels = [self._input_label(r) for r in refs]
            if isinstance(value, list):
                key = "|".join(str(r) for r in refs)
                label = ", ".join(lbl for lbl, _ in labels)
                default = [d for _, d in labels]
            else:
                layer = self._layer(value)
                key = layer.id() if layer is not None else str(value)
                label, default = labels[0]
            name = self._add_input(key, definition, label, default)
            return [Src.fromModelParameter(name)], depth

        sources = []
        for ref, prod in zip(refs, produced):
            if prod is not None:
                sources.append(Src.fromChildOutput(*prod))
            else:
                sources.append(Src.fromStaticValue(self._input_label(ref)[1]))
        return sources, depth

    # ── steps ───────────────────────────────────────────────────────────────
    def build(self, steps: List[Dict[str, Any]]) -> QgsProcessingModelAlgorithm:
        Src = QgsProcessingModelChildParameterSource
        children = []
        for index, step in enumerate(steps, start=1):
            alg = self.registry.algorithmById(step["algorithm"])
            if alg is None:
                raise ValueError(f"Algorithm not found: {step['algorithm']}")
            child_id = f"step_{index}"
            child = QgsProcessingModelChildAlgorithm(alg.id())
            child.setChildId(child_id)
            child.setDescription(f"{index}. {step.get('operation') or alg.displayName()}")

            params = step.get("parameters") or {}
            depth = 0
            for definition in alg.parameterDefinitions():
                name = definition.name()
                if definition.isDestination() or params.get(name) is None:
                    continue
                if definition.type() in LAYER_PARAM_TYPES:
                    sources, d = self._layer_sources(definition, params[name])
                    depth = max(depth, d)
                else:
                    sources = [Src.fromStaticValue(params[name])]
                child.addParameterSources(name, sources)

            self.depth[child_id] = depth
            for output_name, layer_id in (step.get("outputs") or {}).items():
                self.producers[layer_id] = (child_id, output_name)
            children.append((child, step))

        # Lay out by depth, then expose results that nothing else consumed
        per_depth: Dict[int, int] = {}
        for child, step in children:
            d = self.depth[child.childId()]
            column = per_depth.get(d, 0)
            per_depth[d] = column + 1
            x, y = _X0 + _X_STEP * column, _CHILD_Y0 + _Y_STEP * d
            child.setPosition(QPointF(x, y))

            model_outputs = {}
            for output_name, layer_id in (step.get("outputs") or {}).items():
                if layer_id in self.consumed:
                    continue
                layer = self.project.mapLayer(layer_id)
                label = layer.name() if layer is not None else f"{child.description()} {output_name}"
                output = QgsProcessingModelOutput(label, label)
                output.setChildId(child.childId())
                output.setChildOutputName(output_name)
                output.setPosition(QPointF(x + 120.0, y + 70.0 + 30.0 * len(model_outputs)))
                model_outputs[label] = output
            if model_outputs:
                child.setModelOutputs(model_outputs)
            self.model.addChildAlgorithm(child)

        self.model.updateDestinationParameters()

        for child, _ in children:
            ok, issues = self.model.validateChildAlgorithm(child.childId())
            if not ok:
                _logger.warning(f"Model step {child.childId()} issues: {issues}")
        return self.model


def build_model(steps: List[Dict[str, Any]], request: str = "") -> QgsProcessingModelAlgorithm:
    """Build a QGIS Processing model from steps returned by collect_steps()."""
    if not steps:
        raise ValueError("There are no successful processing steps to export.")
    return _ModelBuilder(request).build(steps)


def open_in_model_designer(model: QgsProcessingModelAlgorithm):
    """Open *model* in the QGIS Model Designer (the dialog works on a copy)."""
    from processing.modeler.ModelerDialog import ModelerDialog

    dialog = ModelerDialog.create(model)
    dialog.show()
    dialog.raise_()
    dialog.activateWindow()
    return dialog


def default_models_folder() -> str:
    """The user's Processing models folder (models there show in the Toolbox)."""
    try:
        from processing.modeler.ModelerUtils import ModelerUtils

        return ModelerUtils.modelsFolders()[0]
    except Exception:
        return os.path.expanduser("~")


def save_model(model: QgsProcessingModelAlgorithm, path: str) -> bool:
    """Write *model* to *path*.

    Returns True if the file landed in a Processing models folder, in which
    case the Toolbox's Models provider is refreshed so it shows up there.
    """
    if not model.toFile(path):
        raise OSError(f"Could not write model file: {path}")
    try:
        from processing.modeler.ModelerUtils import ModelerUtils

        folders = [os.path.normcase(os.path.abspath(f)) for f in ModelerUtils.modelsFolders()]
        if os.path.normcase(os.path.dirname(os.path.abspath(path))) in folders:
            provider = QgsApplication.processingRegistry().providerById("model")
            if provider is not None:
                provider.refreshAlgorithms()
            return True
    except Exception as e:
        _logger.warning(f"Could not refresh the Models provider: {e}")
    return False


__all__ = [
    "collect_steps",
    "build_model",
    "open_in_model_designer",
    "default_models_folder",
    "save_model",
    "suggested_file_name",
]
